# Defaults
# backtraces_path = "/path/to/neovide_backtraces.log" # see below for the default platform specific location
fork = false
frame = "full"
# idle = true
maximized = false
mouse-cursor-icon = "arrow"
# neovim-bin = "/usr/bin/nvim"                        # in reality found dynamically on $PATH if unset
# no-multigrid = false
# srgb = false
# tabs = true
# theme = "auto"
# title-hidden = true
# vsync = true
# wsl = false

# idle = false
neovim_bin = "/Users/$USER/.local/share/bob/nvim-bin/nvim"
# neovim_bin = "/Users/$USER/.local/bin/km-nvim.sh"
# neovim_bin = "/Users/$USER/.local/bin/lvim.sh"
# neovim_bin = "/Users/$USER/.local/bin/astronvim.sh"
# no-multigrid = true
no-multigrid = false
srgb = true
tabs = true
theme = "dark"
title_hidden=true
# vsync = false
vsync = true
# This defaults to true because out-of-sync rendering on macOS can cause kernel panics (macOS 14.4+) and performance issues for external displays over some hardware such as DisplayLink. If you want to minimize input latency, set this to false with the known aforementioned risks.
wsl = false

# Font
# * [font] table in configuration file contains:
#   * normal: required, FontDescription
#   * bold: optional, SecondaryFontDescription
#   * italic: optional, SecondaryFontDescription
#   * bold_italic: optional, SecondaryFontDescription
#   * features: optional, { "<font>" = ["<string>"] }
#   * size: required,
#   * width: optional,
#   * hinting: optional,
#   * edging: optional,
# * `FontDescription` can be:
#     * a table with two keys `family` and `style`, `family` is required, `style` is optional,
#     * a string, indicate the font family,
#     * an array of string or tables in previous two forms.
# * `SecondaryFontDescription` can be:
#     * a table with two keys `family` and `style`, both are optional,
#     * a string, indicate the font family,
#     * an array of string or tables in previous two forms.
# * Font styles consist of zero or more space separated parts, each parts can be:
#     * pre-defined style name
#         * weight: `Thin`, `ExtraLight`, `Light`, `Normal`, `Medium`, `SemiBold`, `Bold`, `ExtraBold`, `Black`, `ExtraBlack`
#         * slant: `Italic`, `Oblique`
#     * variable font weight: `W<weight>`, e.g. `W100`, `W200`, `W300`, `W400`, `W500`, `W600`, `W700`, `W800`, `W900`
# * Font features are a table with font family as key and an array of string as value, each string is a font feature.
#     * Font feature is a string with format `+<feature>`, `-<feature>` or `<feature>=<value>`, e.g. `+ss01`, `-calt`, `ss02=2`. `+<feature>` is a shorthand for `<feature>=1`, `-<feature>` is a shorthand for `<feature>=0`.
#
# Options
#  * apply to all fonts at once.
#  * are separated from the fonts and themselves through : (colons).
#  * can be one of the following:
#    * hX — Sets the font size to X points, while X can be any (even floating-point) number.
#    * wX (available since 0.11.2) — Sets the width relative offset to be X points, while X can be again any number. Negative values shift characters closer together, positive values shift them further apart.
#    * b — Sets the font bold.
#    * i — Sets the font italic.
#    * #e-X (available since 0.10.2) — Sets edge pixels to be drawn opaquely or with partial transparency, while X is a type of edging:
#      * antialias (default)
#      * subpixelantialias
#      * alias
#    * #h-X (available since 0.10.2) - Sets level of glyph outline adjustment, while X is a type of hinting:
#      * full (default)
#      * normal
#      * slight
#      * none

# MonoLisa
# [font]
# normal = [] # Will use the bundled Fira Code Nerd Font by default
# size = 16.0
# hinting = "full"
# # edging = "subpixelantialias"
# edging = "antialias"
#
# [[font.normal]]
# family = "MonoLisa Nerd Font Mono"
# style = "Regular"
# [[font.italic]]
# family = "MonoLisa Nerd Font Mono"
# style = "Italic"
# [[font.bold]]
# family = "MonoLisa Nerd Font Mono"
# style = "Bold"
# [[font.bold_italic]]
# family = "MonoLisa Nerd Font Mono"
# style = "Bold Italic"

# CommitMono
[font]
size = 16.0
hinting = "full"
# edging = "subpixelantialias"
edging = "antialias"

[[font.normal]]
family = "CommitMonoCustom4 Nerd Font"
style = "Regular"
[[font.italic]]
family = "CommitMonoCustom4 Nerd Font"
style = "Italic"
[[font.bold]]
family = "CommitMonoCustom4 Nerd Font"
style = "Bold"
[[font.bold_italic]]
family = "CommitMonoCustom4 Nerd Font"
style = "Bold Italic"

# bold = "Maple Mono NF Bold"
# italic = "MapleMono-NF-Italic"
# bold_italic = "MapleMono-NF-BoldItalic"

# normal = "BerkeleyMono Nerd Font"
# normal = "GeistMono Nerd Font Mono"
# normal = "Hack Nerd Font Mono"
# normal = "Cascadia Code Light"
# normal = "Iosevka SS08 Light"
# normal = "JetBrainsMono Nerd Font"
# normal = "BlexMono Nerd Font Mono"
# normal = "RecursiveMnCslSt Nerd Font"
# normal = "RecMonoLinearNFM"
# normal = "RecMonoLinear Nerd Font Mono"
# normal = "Recursive Mono Linear Static"
# normal = "CaskaydiaCove Nerd Font Mono"
# normal = "FantasqueSansMono Nerd Font Mono"
# normal = "CommitMono Nerd Font Mono"
# normal = "CommitMonoCustom21 Nerd Font"
# normal = "CommitMonoThesimpledev Nerd Font"
# normal = "VictorMono Nerd Font"
# normal = "Input Mono Condensed"
# normal = "Input Mono Compressed"
# normal = "Input Mono Narrow"
# normal = "Lilex Nerd Font Mono"
# normal = "LilexExtraThick Nerd Font Mono"
# normal = "M+CodeLat50 Nerd Font Mono"
# normal = "Martian Mono"
# normal = "CommitMonoThesimpledev Nerd Font"
# normal = "DaddyTimeMono Nerd Font Mono"
# normal = "D2Coding"
# normal = "Cousine Nerd Font Mono"
# noraml = "DejaVuSansMono Nerd Font Mono"

# nortmal = "0xProto Nerd Font Mono"
# italic = "0xProtoNFM-Italic"
# bold = "0xProtoNFM-Bold"


# normal = "VictorMono Nerd Font Mono"
# bold = "VictorMono Nerd Font Mono"
# italic = "VictorMono Nerd Font Mono"
# bold_italic = "VictorMono Nerd Font Mono"

# normal = "Monaspace Neon"
# bold = "Monaspace Neon"
# italic = "Monaspace Xenon"

# normal = "MonaspiceNe Nerd Font Mono"
# bold = "MonaspiceNe Nerd Font Mono"
# italic = "MonaspiceXe Nerd Font Mono"
# bold_italic = "MonaspiceXe Nerd Font Mono"
# hinting = true

# allow_float_size = true
[font.features]
"MonoLisa Nerd Font Mono" = [
  "+calt",
  "+liga",
  "+zero",
  "+ss02",
  "-ss01",
  "+ss02",
  "-ss03",
  "+ss04",
  "+ss05",
  "-ss06",
  "-ss07",
  "-ss08",
  "-ss09",
  "+ss10",
  "+ss11",
  "+ss12",
  "-ss13",
  "+ss14",
  "+ss15",
  "+ss16",
  "+ss17",
  "+ss18"
]
  MonoLisa = [
    "+calt",
    "+liga",
    "+zero",
    "+ss02",
    "-ss01",
    "+ss02",
    "-ss03",
    "+ss04",
    "+ss05",
    "-ss06",
    "-ss07",
    "-ss08",
    "-ss09",
    "+ss10",
    "+ss11",
    "+ss12",
    "-ss13",
    "+ss14",
    "+ss15",
    "+ss16",
    "+ss17",
    "+ss18"
  ]
  "MonaspiceNe Nerd Font Mono" = [
    "+calt",
    "+liga",
    "+zero",
    "+dlig",
    "+ss01",
    "+ss02",
    "+ss03",
    "+ss04",
    "+ss05",
    "+ss06",
    "+ss07",
    "+ss08"
  ]
  "MonaspiceXe Nerd Font Mono" = [
    "+ss01",
    "+ss02",
    "+ss03",
    "+ss04",
    "+ss05",
    "+ss06",
    "+ss07",
    "+ss08",
    "+calt",
    "+liga",
    "+dlig",
  ]
  "Maple Mono NF" = [
    # -calt; +cv01; +cv07; +cv34; +cv61; +cv62; +cv64; +ss03; +ss08; +ss09; +ss10; +ss11; +zer
    # "-calt", # default ligatures
    # "+cv01",# remove gaps
    # "+cv02",# alt a
    # "+cv04", # alt l
    # "+cv06", # alt i (unsure about this one)
    # "+cv07", # alt J
    # "+cv08", # alt r
    # "+cv61", # alt comma
    # "+cv62", # alt ?
    # "+cv64", # alt left and right arrow
    # "+cv34", # italic loop k
    # "+cv34", # italic loop k
    # "+cv35", # alt l
    # "+ss03", # arbitrary tag
    # "+ss10", # approx. equal
    # "+ss11", # |==
    "-calt",
    "+cv01;",
    "+cv07;",
    "+cv08;",
    "+cv34;",
    "+cv61;",
    "+cv62;",
    "+cv64;",
    "+ss03;",
    "+ss08;",
    "+ss09;",
    "+ss10;",
    "+ss11;",
    "+zero"
  ]
