# See https://github.com/openai/codex/blob/main/docs/config.md
# Also https://github.com/openai/codex/blob/main/docs/config.md#feature-flags
sandbox_mode = "workspace-write"
approval_policy = "on-request"

[features]
shell_snapshot = true
web_search_request = true
